TeraNetSystem/TeraNetSystem.Web/Areas/Administration/Controllers/AdminNewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using TeraNetSystem.Data;
using TeraNetSystem.Models;
using TeraNetSystem.Web.Controllers;
using TeraNetSystem.Web.Models;
using System.IO;
using TeraNetSystem.Web.Areas.Administration.Models;

namespace TeraNetSystem.Web.Areas.Administration.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminNewsController : NewsController
    {
        private const int PageSize = 3;
        public AdminNewsController(ITeraNetData data)
            : base(data)
        {
        }

        private IQueryable<NewsViewModel> GetNews(int page, int? count = null)
        {
            int newsToTake = count != null ? count.GetValueOrDefault(1) : PageSize;

            var allNews = this.Data.News.All();
            var news = allNews
                       .Select(NewsViewModel.FromNews)
                       .OrderByDescending(n => n.DateCreated)
                       .Skip((page - 1) * PageSize)
                       .Take(newsToTake);


            ViewBag.Pages = Math.Ceiling((double)allNews.Count() / PageSize);
            ViewBag.PageNumber = page;

            return news;
        }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult ListNews(int? page)
        {
            var pageNumber = page.GetValueOrDefault(1);
            pageNumber = pageNumber < 1 ? 1 : pageNumber;

            return View(GetNews(pageNumber));
        }



        [HttpGet]
        public ActionResult Edit(int? id)
        {
            return GetSelectedNews(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NewsViewModel editedNews)
        {
            if (editedNews.Title != null && editedNews.Content != null)
            {
                var newsToEdit = this.Data.News.All().FirstOrDefault(n => n.Id == editedNews.Id);
                newsToEdit.Title = editedNews.Title;
                newsToEdit.Content = editedNews.Content;

                this.Data.SaveChanges();
                TempData["Success"] = "News editted successfully";
                return RedirectToAction("ListNews");
            }
            else
            {
                TempData["Error"] = "Please provide correct information!";
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var selectedNews = this.Data.News.All().FirstOrDefault(n => n.Id == id);

            if (selectedNews == null)
            {
                TempData["Erorr"] = String.Format("News woth ID {0} NOT FOUND!", id);
            }
            else
            {
                this.Data.News.Delete(selectedNews);
                this.Data.SaveChanges();
                TempData["Success"] = "News deleted successfully";
            }

            return RedirectToAction("ListNews");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewsCreateModel newsToCreate)
        {

            if (ModelState.IsValid)
            {
                var currentUserId = this.User.Identity.GetUserId();

                string imagePath = string.Empty;
                string imageExt = string.Empty;

                if (newsToCreate.Image == null)
                {
                    imagePath = "~/Content/images/news.png";
                }
                else
                {
                    string imageName = Guid.NewGuid().ToString();
                    imageExt = Path.GetExtension(newsToCreate.Image.FileName);
                    
                    imagePath = "~/Files/news/" +  imageName + imageExt;
                    newsToCreate.Image.SaveAs(Server.MapPath(imagePath));
                }

                var newNews = new News()
                {
                    Title = newsToCreate.Title,
                    Content = newsToCreate.Content,
                    AuthorId = currentUserId,
                    ImagePath = imagePath
                };

                this.Data.News.Add(newNews);
                this.Data.SaveChanges();
                TempData["Success"] = "News added successfully!!";

            }
            else
            {
                TempData["Error"] = "Please provide correct information!";
            }

            return RedirectToAction("ListNews");
        }
    }
}

TeraNetSystem/TeraNetSystem.Web/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeraNetSystem.Data;
using TeraNetSystem.Web.Models;

namespace TeraNetSystem.Web.Controllers
{
    public class NewsController : BaseController
    {
        public NewsController(ITeraNetData data)
            :base(data)
        {
        }

        [ChildActionOnly]
        protected ActionResult GetSelectedNews(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var selectedNews = this.Data.News.All().Select(NewsViewModel.FromNews).FirstOrDefault(n => n.Id == id);

            if (selectedNews == null)
            {
                TempData["Error"] = string.Format("News with Id {0} NOT FOUND!", id);
                return RedirectToAction("ListNews");
            }

            return View(selectedNews);
        }
 
        [HttpGet]
        public ActionResult NewsDetails(int? id)
        {
            return GetSelectedNews(id);
        }
    }
}

TeraNetSystem/TeraNetSystem.Web/Areas/Administration/Views/AdminNews/Create.cshtml
@model TeraNetSystem.Web.Areas.Administration.Models.NewsCreateModel
@{
    ViewBag.Title = "Add news";
}


@using (Html.BeginForm("Create", "AdminNews", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal admin-panel", enctype = "multipart/form-data" }))
{
    <h2>@ViewBag.Title</h2>

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="content-box box-default">
        <div class="row">
            <div class="col-md-4">
                <img src="@Url.Content("~/Content/images/news.png")" alt="OfficeImage" class="img-responsive" id="image-tag">
            </div>
            <div class="col-md-8">
                <div class="row">
                    <h4 class="content-box-title">
                        @Html.LabelFor(m => m.Title)
                    </h4>
                </div>
                <div class="row col-lg-offset-4 margin-bottom">
                    @Html.EditorFor(m => m.Title)
                </div>
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                
                <div class="row margin-10">
                    <span class="">
                        <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Content)</span>
                        @Html.TextAreaFor(m => m.Content, 10, 400, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
                    </span>
                </div>

                <div class="row  margin-10">
                    <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Image)</span>
                    <span>
                        <input type="file" name="Image" id="input-image" value=" " class="form-control col-lg-4" />
                    </span>
                    @Html.ValidationMessageFor(m => m.Image, "", new { @class = "text-danger" })
                </div>

                <button type="submit" class="button button-rounded button-flat-primary pull-left">
                    <i class="fa fa-upload">
                        Add
                    </i>
                </button>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
}

@section scripts
{
    @Scripts.Render("~/Scripts/PagesJs/ImageReloader.js")
}

TeraNetSystem/TeraNetSystem.Web/Areas/Administration/Views/AdminNews/Edit.cshtml
@model TeraNetSystem.Web.Models.NewsViewModel
@{
    ViewBag.TItle = "Edit news";
}

<div class="admin-panel">
    <h2>@ViewBag.Title</h2>
    @using (Html.BeginForm("Edit", "News", new { id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_NewsPartial")
    }
</div>

TeraNetSystem/TeraNetSystem.Web/Areas/Administration/Views/AdminNews/ListNews.cshtml
@model IEnumerable<TeraNetSystem.Web.Models.NewsViewModel>
@{
    ViewBag.TItle = "List news";
}

<h2>@ViewBag.Title</h2>
<br />
@foreach (var office in @Model)
{
    Html.RenderPartial("_NewsPartial", office);
}
<a href="@Url.Action("Create", "AdminNews")" class="button button-block button-rounded button-primary button-large">Add news</a>