TeraNetSystem/TeraNetSystem.Web/Areas/Office/Models/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using TeraNetSystem.Models;

namespace TeraNetSystem.Web.Areas.Office.Models
{
    public class RequestViewModel
    {
        public static Expression<Func<Request, RequestViewModel>> FromRequest
        {
            get
            {
                return r => new RequestViewModel
                {
                    Id = r.Id.ToString(),
                    SubscriptionName = r.Subscription.SubscriptionName,
                    TownName = r.Town.TownName,
                    Address = r.Address,
                    FullName = string.Format("{0} {1}",r.FirstName, r.LastName),
                    PhoneNumber = r.PhoneNumber
                };
            }
        }

        public string Id { get; set; }

        [DisplayName("Town: ")]
        public string TownName { get; set; }

        [DisplayName("Subscription plan: ")]
        public string SubscriptionName { get; set; }

        [DisplayName("Address: ")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }

        [DisplayName("Full name: ")]
        public string FullName { get; set; }

        [DisplayName("Phone number: ")]
        public string PhoneNumber { get; set; }
    }
}

TeraNetSystem/TeraNetSystem.Web/Areas/Office/Controllers/RequestController.cs
namespace TeraNetSystem.Web.Areas.Office.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using Microsoft.AspNet.Identity;

    using TeraNetSystem.Web.Controllers;
    using TeraNetSystem.Web.Areas.Office.Models;
    using TeraNetSystem.Data;
    using System.Net;

    public class RequestController : OfficeController
    {
        private const int PageSize = 5;

        public RequestController(ITeraNetData data)
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult ListRequests(int? id)
        {
            int pageNumber = id.GetValueOrDefault(1);

            var currentUserId = this.User.Identity.GetUserId();
            var currentOfficeTownId = this.Data.Users.All().FirstOrDefault(u => u.Id == currentUserId).TownId;

            var requestForCurrentTown = this.Data.Requests.All().Where(r => r.Approved == false);
            if (User.IsInRole("OfficeMan"))
            {
                requestForCurrentTown = this.Data.Requests.All().Where(r => r.TownId == currentOfficeTownId);
            }

            var requestsPage = requestForCurrentTown.OrderBy(x => x.Id)
                             .Skip((pageNumber - 1) * PageSize)
                             .Take(PageSize)
                             .Select(RequestViewModel.FromRequest)
                             .ToList();

            ViewBag.Pages = Math.Ceiling((double)requestForCurrentTown.Count() / PageSize);
            ViewBag.PageNumber = pageNumber;

            return View(requestsPage);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var selectedRequests = this.Data.Requests.All().Select(RequestViewModel.FromRequest).FirstOrDefault(t => t.Id.ToString() == id);

            if (selectedRequests == null)
            {
            }

            return View(selectedRequests);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var requestToBeDeleted = this.Data.Requests.GetById(new Guid(id));

            this.Data.Requests.Delete(requestToBeDeleted);
            this.Data.SaveChanges();

            TempData["Success"] = String.Format("Request with id - {0}  has been deleted successully!", id);

            return RedirectToAction("ListRequests");
        }

        [HttpGet]
        public ActionResult Transfer(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var selectedRequestsAsTask = this.Data.Requests.All().Select(TaskViewModel.FromRequest).FirstOrDefault(t => t.Id.ToString() == id);

            var networkersList = this.GetNetworkers(selectedRequestsAsTask.TownName);

            selectedRequestsAsTask.Netwrokers = networkersList;

            this.Data.Requests.All().FirstOrDefault(r => r.Id.ToString() == id).Approved = true;
            this.Data.SaveChanges();

            return View(selectedRequestsAsTask);
        }

    }
}

TeraNetSystem/TeraNetSystem.Web/Areas/Office/Views/Request/Details.cshtml
@using TeraNetSystem.Web.Areas.Office.Models
@model RequestViewModel

@{
    ViewBag.Title = "Details";
}

<div class="admin-panel">
    <div class="row">
        @Html.Partial("_RequestPartial")

    </div>

    <a class="button button-rounded button-flat-caution button-large" href="@Url.Action("ListRequests", "Request")">
        Back to list
    </a>
</div>

TeraNetSystem/TeraNetSystem.Web/Areas/Office/Views/Request/ListRequests.cshtml
@using TeraNetSystem.Web.Areas.Office.Models;
@model IEnumerable<RequestViewModel>

@{
    ViewBag.Title = "List requests";
}

<div class="admin-panel">
    <h2>@ViewBag.Title</h2>
    @if (@Model.Count() == 0)
    {
        <h1 class="text-center text-info">No pending requests!</h1>
    }
    else
    {
        for (int i = 1; i <= ViewBag.Pages; i++)
        {
            <a class="button button-flat@( i==ViewBag.PageNumber ? "-primary" : "") button-circle" href="@Url.Action("ListRequests", new { id = i })">@i</a>
        }
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Town</th>
                    <th>Client</th>
                    <th>Subscription plan</th>
                    <th>Details</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var currnetSubscription in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(t => currnetSubscription.TownName)</td>
                        <td>@Html.DisplayFor(t => currnetSubscription.FullName)</td>
                        <td>@Html.DisplayFor(t => currnetSubscription.SubscriptionName)</td>
                        <td>
                            <a class="button button-rounded button-flat-primary" href="@Url.Action("Details", "Request", new { id = currnetSubscription.Id})">
                                <i class="fa fa-info">
                                    Details
                                </i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

TeraNetSystem/TeraNetSystem.Web/Areas/Office/Views/Request/Transfer.cshtml
@model TeraNetSystem.Web.Areas.Office.Models.TaskViewModel
@{
    ViewBag.Title = "Transfer requst to task";
}

<div class="admin-panel">
    <h2>
        @ViewBag.Title
    </h2>
    <div class="row">
        @using (Html.BeginForm("Create", "Task", null, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.Partial("_TaskPartial")
        }
    </div>

    <a class="button button-rounded button-flat-caution button-large" href="@Url.Action("ListRequests", "Request")">
        Back to list
    </a>
</div>