TeraNetSystem/TeraNetSystem.Web/Controllers/ClientPaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;

using TeraNetSystem.Data;
using TeraNetSystem.Web.Models;
using System.Net;

namespace TeraNetSystem.Web.Controllers
{
    [Authorize]
    public class ClientPaymentController : BaseController
    {
        private const int PageSize = 5;

        public ClientPaymentController(ITeraNetData data)
            :base(data)
        {
        }

        [HttpGet]
        public ActionResult MyPayments(int? page)
        {
            var currentUserId = User.Identity.GetUserId();

            var searchedPayments = this.Data.Payment.All()
                                .Select(PaymentViewModel.FromPayment)
                                .Where(u => u.Client.Id == currentUserId);

            int pageNumber = page.GetValueOrDefault(1);

            if (pageNumber < 1)
            {
                pageNumber = 1;
            }
           
            var searchedPaymentsPage = searchedPayments
                          .OrderByDescending(x => x.DateCreated)
                          .ThenByDescending(x=>x.PerMonth)
                          .Skip((pageNumber - 1) * PageSize)
                          .Take(PageSize)
                          .ToList();

            ViewBag.Pages = Math.Ceiling((double)searchedPayments.Count() / PageSize);
            ViewBag.PageNumber = pageNumber;

            return View(searchedPaymentsPage);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var searchedPayment = this.Data.Payment.All().Select(PaymentViewModel.FromPayment).FirstOrDefault(p => p.Id == id);
            if (searchedPayment == null)
            {
                TempData["Error"] = "No payment with such ID";
                return RedirectToAction("MyPayments");
            }

            return View(searchedPayment);
        }
    }
}

TeraNetSystem/TeraNetSystem.Web/Controllers/ServicesController.cs
using CaptchaMvc.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeraNetSystem.Data;
using TeraNetSystem.Models;
using TeraNetSystem.Web.Areas.Administration.Models;
using TeraNetSystem.Web.Models;

namespace TeraNetSystem.Web.Controllers
{
    public class ServicesController : BaseController
    {
        public ServicesController(ITeraNetData data)
            : base(data)
        {
        }

        [OutputCache(Duration= 60*60*24)]
        private List<SelectListItem> TownsList()
        {
            var towns = this.Data.Towns.All().Select(TownCreateModel.FromOffice);
            var selectedList = new List<SelectListItem>();

            foreach (var item in towns)
            {
                selectedList.Add(new SelectListItem() { Value = item.Id.ToString(), Text = item.Name });
            }

            return selectedList;
        }

        [HttpGet]
        public ActionResult All()
        {
            var services = this.Data.Subscriptions.All().Select(SubscriptionViewModel.FromSubscription);

            return View(services);
        }

        [HttpGet]
        public ActionResult Request(int? id)
        {
            var serviceId = id.GetValueOrDefault(1);

            var towns = this.TownsList();

            var createModel = new ServiceRequestModel() { Towns = towns, SubscriptionId = serviceId };
            return View(createModel);
        }

        [HttpPost, CaptchaVerify("Code is not valid")]
        [ValidateAntiForgeryToken]
        public ActionResult Request(ServiceRequestModel request)
        {

            if (ModelState.IsValid)
            {
                var createdRequest = new Request()
                {
                    TownId = request.TownId,
                    Address = request.Address,
                    FirstName = request.FirstName,
                    LastName = request.LastName,
                    SubscriptionId = request.SubscriptionId,
                    PhoneNumber = request.Phone
                };

                this.Data.Requests.Add(createdRequest);
                this.Data.SaveChanges();

                TempData["Success"] = String.Format("Request for {0} subscription plan has been successfully send! We will call you in few days!",
                                                    this.Data.Subscriptions.All().FirstOrDefault(s => s.Id == createdRequest.SubscriptionId).SubscriptionName);
            }
            else
            {
                var towns = this.TownsList();

                request.Towns = towns;
                request.RequstCaptcha = string.Empty;

                return View(request);
            }

            return RedirectToAction("All");
        }
    }
}

TeraNetSystem/TeraNetSystem.Web/Views/Shared/Details.cshtml
@model TeraNetSystem.Web.Models.PaymentViewModel

@{
    ViewBag.Title = "Payment details";   
}
<div class="admin-panel">
    <h2>@ViewBag.Title</h2>
    @Html.Partial("_PaymentPartial", Model)
</div>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/NewsDetails.cshtml
@model TeraNetSystem.Web.Models.NewsViewModel
@{
    ViewBag.TItle = "News details";
}

<div class="admin-panel">
    <h2>@ViewBag.Title</h2>
    @Html.Partial("_NewsPartial")
</div>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css/preload.css")
    @Styles.Render("~/Content/css/bootstrap.css")
    @Styles.Render("~/Content/css/font-awesome.min.css")
    @Styles.Render("~/Content/css/animate.min.css")
    @Styles.Render("~/Content/css/slidebars.css")
    @Styles.Render("~/Content/css/lightbox.css")
    @Styles.Render("~/Content/css/jquery.bxslider.css")
    @Styles.Render("~/Content/css/ErrorSuccessNotifier/ErrorSuccessNotifier.css")
    @Styles.Render("~/Content/css/syntaxhighlighter/shCore.css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/css/style-blue.css")
    @Styles.Render("~/Content/css/width-full.css")
    @Styles.Render("~/Content/css/buttons.css")

    @Styles.Render("~/Content/css/Site.css")

</head>
<body>
    <header id="header-full-top" class="hidden-xs header-full">
        <div class="container">
            <div class="header-full-title">
                <img src="~/Content/images/TeraNetLogo.png" alt="TeraNetLogo" id="logo" />
            </div>
            <nav class="top-nav">
                <ul class="top-nav-social hidden-sm">
                    <li><a href="https://www.facebook.com/TeraNet2007" class="animated fadeIn facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="animated fadeIn linkedin"><i class="fa fa-linkedin"></i></a></li>
                </ul>
                @Html.Partial("_LoginPartial")

            </nav>
        </div>
    </header>
    <nav class="navbar navbar-static-top navbar-default navbar-header-full" role="navigation" id="header">
        <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { Area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Subscriptions", "All", "Services", new { Area = string.Empty }, null)</li>
                    <li>@Html.ActionLink("Contact", "AllOffices", "Contact", new { Area = string.Empty }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My payments", "MyPayments", "ClientPayment", new { Area = string.Empty }, null)</li>

                        if (User.IsInRole("NetworkMan") || User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Network</a>
                                <ul class="dropdown-menu dropdown-menu-left">
                                    <li>@Html.ActionLink("Tasks", "ListTasks", "Task", new { Area = "Office" }, null)</li>
                                </ul>
                            </li>
                        }
                        if (User.IsInRole("OfficeMan") || User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Office</a>
                                <ul class="dropdown-menu dropdown-menu-left">
                                    <li>@Html.ActionLink("Requests", "ListRequests", "Request", new { Area = "Office" }, null)</li>
                                    <li>@Html.ActionLink("Create payment", "ListUsers", "Payment", new { Area = "Office" }, null)</li>
                                    <li>@Html.ActionLink("List payments", "ListPayments", "Payment", new { Area = "Office" }, null)</li>
                                    <li>@Html.ActionLink("Register Client", "Register", "Account", new { Area = "" }, null)</li>
                                </ul>
                            </li>
                        }
                        if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Admin</a>
                                <ul class="dropdown-menu dropdown-menu-left">
                                    <li>@Html.ActionLink("Towns", "ListTowns", "Town", new { Area = "Administration" }, null)</li>
                                    <li>@Html.ActionLink("Offices", "ListOffices", "Office", new { Area = "Administration" }, null)</li>
                                    <li>@Html.ActionLink("Subscriptions", "ListSubscriptions", "Subscription", new { Area = "Administration" }, null)</li>
                                    <li>@Html.ActionLink("News", "ListNews", "AdminNews", new { Area = "Administration" }, null)</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
            </div><!-- navbar-collapse -->
        </div><!-- container -->
    </nav>
    <div class="container body-content">
        @if (@TempData["Error"] != null)
        {
            <div class="PanelNotificationBox PanelError">@TempData["Error"]</div>
        }
        @if (@TempData["Success"] != null)
        {
            <div class="PanelNotificationBox PanelSuccess">@TempData["Success"]</div>
        }

        @RenderBody()
    </div>
    <aside id="footer-widgets">
        <div class="container">
            <div class="row margin-top margin-bottom">
                <div class="col-md-4">
                    @Html.Partial("_SitemapPartial")
                </div>
                <div class="col-md-3 col-md-offset-1">
                    <div class="footer-widget">
                        <h3 class="footer-widget-title ">Links</h3>
                        <ul class="list-unstyled">
                            <li><a href="https://www.facebook.com/TeraNet2007" class="btn-social solid facebook"><i class="fa fa-facebook"></i>Facebook</a></li>
                            <li><a href="#" class="btn-social solid linkedin"><i class="fa fa-linkedin"></i>Linkedin</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer-widget">
                        <h3 class="footer-widget-title">On Connection Probles</h3>
                        <ul class="list-unstyled">
                            <li>Call Center</li>
                            <li>+359 889 888 999</li>
                        </ul>

                    </div>
                </div>
            </div> <!-- row -->

        </div> <!-- container -->
    </aside>
    <footer id="footer">
        <p>St. Todorov © 2014| Open source project <a href="https://github.com/sttodorov/TeraNetSystem">Github</a>  </p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", false)
</body>
</html>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_ListPaymentsPartial.cshtml
@model IEnumerable<TeraNetSystem.Web.Models.PaymentViewModel>

@foreach (var payment in Model)
{
    
    <ul class="list-unstyled">
        <li class="row">
            <span class="col-lg-3 no-padding">@Html.LabelFor(m => payment.DateCreated)</span>
            @Html.DisplayFor(m => payment.DateCreated)
        </li>
        <li class="row">
            <span class="col-lg-3 no-padding">@Html.LabelFor(m => payment.Client.UserName)</span>
           @Html.DisplayFor(m => payment.Client.UserName)
        </li>
        <li class ="row">
            <span class="col-lg-3 no-padding">@Html.LabelFor(m => payment.PerMonth)</span>
            @Html.DisplayFor(m => payment.PerMonth)
        </li>
    </ul>
}

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_NewsPartial.cshtml
@model TeraNetSystem.Web.Models.NewsViewModel

<div class="content-box box-default margin-top">
    <div class="row">
        <div class="col-md-4">
            <img src="@Url.Content(Model.ImagePath)" alt="OfficeImage" class="img-responsive" width="250">
        </div>
        <div class="col-md-8">
            <div class="row ">
                @Html.LabelFor(m => m.Title)
                @if (ViewBag.Title == "Edit news")
                {
                    <center> @Html.EditorFor(m => m.Title, new { Value = Model.Title })</center>
                    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                }
                else
                {
                    <h3 class="margin-bottom ">
                        @Html.DisplayFor(m => m.Title)
                    </h3>
                }
            </div>

            <ul class="list-unstyled text-left">
                @if (ViewBag.TItle != "List news" && ViewBag.TItle != "Home page")
                {
                    <li class="row">
                        <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.DateCreated)</span>
                        @Html.DisplayFor(m => m.DateCreated)
                    </li>
                    <li class="row">
                        <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Author.FullName)</span>
                        @Html.DisplayFor(m => m.Author.FullName)
                    </li>
                }

                <li class="row">
                    <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Content)</span>
                    <span class="col-lg-9 no-padding">
                        @if (ViewBag.Title == "Edit news")
                        {
                            @Html.TextArea("Content", Model.Content, 10, 600, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
                        }
                        else
                        {
                            if (ViewBag.TItle == "List news")
                            {
                                <p>@(Model.Content.Length > 200 ? Model.Content.Substring(0, 197) + "..." : Model.Content)</p>
                            }
                            else
                            {
                                @Html.DisplayFor(m => m.Content)
                            }
                        }
                    </span>
                </li>
            </ul>
            @if (ViewBag.Title == "List news")
            {
                <div class="row">
                    <a class="button button-rounded button-flat-primary" href="@Url.Action("NewsDetails", "AdminNews", new { id = @Model.Id })">
                        <i class="fa fa-info">
                            Details
                        </i>
                    </a>
                </div>
            }
            <div class="row margin-top col-lg-offset-3">
                @if (ViewBag.Title == "News details" && User.IsInRole("Admin"))
                {

                    <span class="col-lg-4">
                        <a class="button button-rounded button-flat-primary" href="@Url.Action("Edit", "AdminNews", new { id = @Model.Id })">
                            <i class="fa fa-refresh">
                                Edit
                            </i>
                        </a>
                    </span>
                    <span class="col-lg-4">
                        @using (Html.BeginForm("Delete", "News", new { id = Model.Id }, FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            <button class="button button-rounded button-flat-caution" type="submit">
                                <i class=" fa fa-warning no-margin no-padding">
                                    Delete
                                </i>
                            </button>
                        }
                    </span>
                }

                @if (ViewBag.Title == "Edit news")
                {

                    <span class="col-lg-4">
                        <button class="button button-rounded button-flat-primary" type="submit">
                            <i class=" fa fa-upload no-margin no-padding">
                                Apply
                            </i>
                        </button>
                    </span>
                    <span class="col-lg-4">
                        <a class="button button-rounded button-flat-caution" href="@Url.Action("ListNews", "AdminNews", new { id = @Model.Id })">
                            <i class="fa fa-warning">
                                Cancel
                            </i>
                        </a>
                    </span>
                }
            </div>
        </div>
    </div>

</div>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_OfficePartial.cshtml
@model TeraNetSystem.Web.Models.OfficeViewModel
@if (ViewBag.Title != "Contacts")
{
    <h2>
        @ViewBag.Title
    </h2>
}

<div class="content-box box-default margin-top">
    <div class="row">
        <div class="col-md-4">
            <img src="@Url.Content(Model.ImagePath)" alt="OfficeImage" class="img-responsive" width="250">
        </div>
        <div class="col-md-8">
            <div class="row margin-bottom">
                @Html.LabelFor(m => m.Name)
                @if (ViewBag.Title == "Edit office")
                {
                    <center> @Html.EditorFor(m => m.Name, new { Value = Model.Name })</center>
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                }
                else
                {
                    <h3 class="margin-bottom ">
                        @Html.DisplayFor(m => m.Name)
                    </h3>
                }
            </div>


            <ul class="list-unstyled text-left">
                <li class="row">
                    <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Id)</span>
                    @Html.DisplayFor(m => m.Id)
                </li>
                <li class="row">
                    <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.TownName)</span>
                    @Html.DisplayFor(m => m.TownName)
                </li>
                <li class="row">
                    <span class="col-lg-3 no-padding">@Html.LabelFor(m => m.Address)</span>
                    @if (ViewBag.Title == "Edit office")
                    {
                        @Html.EditorFor(m => m.Address, new { Value = Model.Address })
                        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                    }
                    else
                    {
                        @Html.DisplayFor(m => m.Address)
                    }
                </li>
                <li class="row">
                    <span class="col-lg-3 no-padding">
                        @Html.LabelFor(m => m.Phone)
                    </span>
                    @if (ViewBag.Title == "Edit office")
                    {
                        @Html.EditorFor(m => m.Phone, new { Value = Model.Phone })
                        @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                        @Html.HiddenFor(m => m.TownName)
                    }
                    else
                    {
                        @Html.DisplayFor(m => m.Phone)
                    }
                </li>
            </ul>
            @if (ViewBag.Title == "Office details")
            {
                @Html.Partial("_AdminOfficePartial", Model)
            }
        </div>
    </div>
</div>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_PaymentPartial.cshtml
@model TeraNetSystem.Web.Models.PaymentViewModel

<div class="content-box box-default margin-top col-lg-8">
    <div class="row">
        @if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "Payment" && ViewBag.Title!="Create payment")
        {
            <h4>Id: @Html.DisplayFor(m => m.Id)</h4>
        }
        <h4>Client info:</h4>
        <ul class="list-unstyled text-left col-lg-offset-1">
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.DateCreated)</span>
                @Html.DisplayFor(m => m.DateCreated)
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.PerMonth)</span>
                @if (ViewBag.Title == "Payment details")
                {
                    @Html.DisplayFor(m => m.PerMonth)
                }
                else
                {
                    @Html.EnumDropDownListFor(m => m.PerMonth, new { @class = "form-control", id = "MonthDropdown" })
                    @Html.ValidationMessageFor(m => m.PerMonth, "", new { @class = "text-danger" })
                }

            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Client.UserName)</span>
                @Html.DisplayFor(m => m.Client.UserName)
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Client.TownName)</span>
                @Html.DisplayFor(m => m.Client.TownName)
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Client.Address)</span>
                <span class="col-lg-5 no-padding">
                    @Html.DisplayFor(m => m.Client.Address)
                </span>
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Client.Subscription.SubscriptionName)</span>
                @Html.DisplayFor(m => m.Client.Subscription.SubscriptionName)
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Client.Subscription.Price)</span>
                @Html.DisplayFor(m => m.Client.Subscription.Price)
            </li>
        </ul>
        <h4>Office info:</h4>
        <ul class="list-unstyled text-left col-lg-offset-1">

            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Office.TownName)</span>
                @Html.DisplayFor(m => m.Office.TownName)
            </li>
            <li class="row margin-10">
                <span class="col-lg-6 no-padding">@Html.LabelFor(m => m.Office.Address)</span>
                <span class="col-lg-5 no-padding">
                    @Html.DisplayFor(m => m.Office.Address)
                </span>
            </li>
        </ul>
        @if (ViewBag.Title != "Payment details")
        {
            <div class="row margin-10" id="buttonsBlock">
                @Html.HiddenFor(m => m.Client.Id)
                @Html.HiddenFor(m => m.Office.Id)
                <button class="button button-rounded button-flat-primary" type="submit" id="btnRegisterPayment">
                    <i class=" fa fa-upload no-margin no-padding">
                        Pay
                    </i>
                </button>
                <a class="button button-rounded button-flat-caution" href="@Url.Action("ListUsers", "Payment")">
                    Cancel
                </a>
            </div>
        }
    </div>
</div>

TeraNetSystem/TeraNetSystem.Web/Views/Shared/_SitemapPartial.cshtml
<h3 class="footer-widget-title">Sitemap</h3>
<div class="col-md-4">
    <ul class="list-unstyled ">
        <li>@Html.ActionLink("Home", "Index", "Home", new { Area = string.Empty }, null)</li>
        <li>@Html.ActionLink("Services", "All", "Services", new { Area = string.Empty }, null)</li>
        <li>@Html.ActionLink("Contact", "AllOffices", "Contact", new { Area = string.Empty }, null)</li>
        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("My payments", "MyPayments", "ClientPayment", new { Area = string.Empty }, null)</li>
        }
        <li><a href="/Careers">Careers</a></li>
        <li><a href="/TermsOfUse">Terms of use</a></li>
    </ul>
</div>
@if (User.IsInRole("Admin") || User.IsInRole("OfficeMan") || User.IsInRole("NetworkMan"))
{
    <div class="col-md-5">
        <ul class="list-unstyled ">
            <li>@Html.ActionLink("Tasks", "ListTasks", "Task", new { Area = "Office" }, null)</li>
            @if (User.IsInRole("OfficeMan") || User.IsInRole("Admin"))
            {
                <li>@Html.ActionLink("Requests", "ListRequests", "Request", new { Area = "Office" }, null)</li>
                <li>@Html.ActionLink("Create payment", "ListUsers", "Payment", new { Area = "Office" }, null)</li>
                <li>@Html.ActionLink("List payments", "ListPayments", "Payment", new { Area = "Office" }, null)</li>
                <li>@Html.ActionLink("Register Client", "Register", "Account", new { Area = "" }, null)</li>
            }
        </ul>
    </div>
    if (User.IsInRole("OfficeMan") || User.IsInRole("Admin"))
    {
        <div class="col-md-3">
            <ul class="list-unstyled ">
                <li>@Html.ActionLink("Towns", "ListTowns", "Town", new { Area = "Administration" }, null)</li>
                <li>@Html.ActionLink("Offices", "ListOffices", "Office", new { Area = "Administration" }, null)</li>
                <li>@Html.ActionLink("Subscriptions", "ListSubscriptions", "Subscription", new { Area = "Administration" }, null)</li>
                <li>@Html.ActionLink("News", "ListNews", "News", new { Area = "Administration" }, null)</li>
            </ul>
        </div>
    }
}